name: Python Test

on:
  push:
    branches:
      - main  # Endre dette til navnet på din hovedgren

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v2
      with:
        path: .C:\Users\ander\Desktop\Software Engineering\Oblig3\SofwareEngineeringOblig3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Velg ønsket Python-versjon

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run Tests
      run: pytest  # Dette er kommandoen som kjører testene

