name: Python Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Velg Python-versjonen du trenger

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Bytt ut med din avhengighetsfil

    - name: Run Tests
      run: pytest  # Dette kommandoen som kjører testene

